docs_dir: docs/book
site_dir: docs/html
extra:
  project: API
  current_version: v4
  versions:
    - v4
nav:
  - Home: index.md
  - v4:
      - Introduction:
          - "Introduction": v4/introduction/introduction.md
          - "Server Requirements": v4/introduction/server-requirements.md
          - "File Structure": v4/introduction/file-structure.md
          - "Packages": v4/introduction/packages.md
      - Installation:
          - "Getting Started": v4/installation/getting-started.md
          - "Composer": v4/installation/composer.md
          - "Configuration Files": v4/installation/configuration-files.md
          - "Doctrine ORM": v4/installation/doctrine-orm.md
          - "Test the Installation": v4/installation/test-the-installation.md
          - "FAQ": v4/installation/faq.md
      - Tutorials:
          - "Creating a book module": v4/tutorials/create-book-module.md
      - Transition from API Tools:
          - "API Tools vs DotKernel API": v4/transition-from-api-tools/api-tools-vs-dotkernel-api.md
site_name: api
site_description: "DotKernel API"
repo_url: "https://github.com/dotkernel/api"
plugins:
  - search
